# Generated by Django 5.2.5 on 2025-08-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите наименование задачи", max_length=255, verbose_name="Наименование задачи"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Укажите описание задачи", null=True, verbose_name="Описание задачи"
                    ),
                ),
                ("is_parent", models.BooleanField(default=False, verbose_name="Родительская задача")),
                ("deadline", models.DateTimeField(verbose_name="Срок исполнения задачи")),
                (
                    "status",
                    models.CharField(
                        choices=[("work", "В работе"), ("completed", "Завершена")],
                        default="work",
                        max_length=10,
                        verbose_name="Статус задачи",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
