# Generated by Django 5.2.5 on 2025-08-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("created", "Создана"), ("work", "В работе"), ("completed", "Завершена")],
                default="created",
                max_length=10,
                verbose_name="Статус задачи",
            ),
        ),
    ]
